{% set name = "std-uritemplate" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/std_uritemplate-{{ version }}.tar.gz
  sha256: ad4cb1d671bcf4a3608b3598c687be4b0929867c53a2d69c105989da6a5a2d4c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python

test:
  imports:
    - stduritemplate
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://github.com/std-uritemplate/std-uritemplate
  summary: std-uritemplate implementation for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/std-uritemplate/std-uritemplate
  doc_url: https://github.com/std-uritemplate/std-uritemplate/blob/main/Readme.md

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/64252
    reason: Dependency for msgraph-sdk
  recipe-maintainers:
    - ianaobi
    - bkreider
  recipe-maintainers:
    - xylar
